services:
  Palworld:
    container_name: Palworld
    image: diceninjagaming/Palworld-docker:latest
    restart: "unless-stopped"
    network_mode: bridge
    ports:
      - 8211:8211/udp
      - 27015:27015/udp
    volumes:
      - /docker_volumes/Palworld_logs:/app/logs
      - /docker_volumes/Palworld_saves:/app/saves
      - /docker_volumes/Palworld_server:/app/server
    environment:
      - SERVER_NAME=DNG Testing
      - SERVER_PASSWORD=DefaultPassword
      - ADMIN_PASSWORD=SecretAdminPassword
      - SERVER_PORT=8211
      - QUERY_PORT=27015
      - TZ=America/New_York
      - USER_ID=1
      - GROUP_ID=1
